### PR TITLE
Prepare to deploy SNAPSHOT build to Sonatype snapshot repo

### PR DESCRIPTION
**Pull request by KengoTODA**
This PR adds necessary files/plugins to deploy SNAPSHOT build to Sonatype snapshot repository.
I've got permission to deploy under `com.worksap` groupId at https://issues.sonatype.org/browse/OSSRH-15031

About changes in Maven build, please refer: http://central.sonatype.org/pages/apache-maven.html
These changes are not enough to deploy stable version, we need to add GPG signature in another PR.

### CODE REVIEW

**Comment by KengoTODA** [comment]
You can see deployed artifacts at https://oss.sonatype.org/content/repositories/snapshots/com/worksap/nlp/sudachi/0.1-SNAPSHOT/

**Comment by KengoTODA** [comment]
Thank you!

**Comment by kazuma-t** [comment]
It seems that `$encrypted_7881e527c02e_key` is missing. Do you know something about it?

**Comment by KengoTODA** [comment]
@kazuma-t We have it, you can check it at https://travis-ci.org/WorksApplications/Sudachi/settings
Note that [secure variable is not used in PR from other repository](https://docs.travis-ci.com/user/environment-variables/#Defining-Variables-in-Repository-Settings).

The current problem in `develop` branch is that; before `deployer` runs Travis deletes decrepted `.travis/settings.xml` so maven cannot work. It's my mistake and I know solution, I will propose fix later.

**Comment by kazuma-t** [comment]
I see. Thank you!

**Pull request merged**
