### PR TITLE
Introduce SonarQube with coverage computed by Jacoco.

### PR DESCRIPTION
**Pull request by KengoTODA**
This PR is based on #7. I also added SonarCloud analysis in pre/post merge build.
You can find analysis result at https://sonarcloud.io/dashboard?id=com.worksap.nlp.sudachi

### CODE REVIEW

**Comment by konifar** [comment]
🆒

**Comment by konifar** [comment]
Gently push 👀

**Comment by KengoTODA** [comment]
@kazuma-t I've updated comment in YML file. I hope this is also ready to merge.

**Comment by KengoTODA** [comment]
Thank you!

**Pull request merged**
