### PR TITLE
Reuse compiled Pattern instances for better performance

### PR DESCRIPTION
**Pull request by KengoTODA**
Currently some classes invoke `String#split(string)` which compiles a `Pattern` instance internally. For reduce the load on CPU, it is better to reuse the `Pattern` instance.

Note that we do not need to apply this optimization to `line.split(",")` nor `text.split("/")`, due to [Lightweight implementation of String.split for simple use case](https://bugs.java.com/bugdatabase/view_bug.do?bug_id=6840246).

### How this change affects the performance

I made a JMH microbenchmark for the `DictionaryBuilder` class.

In my local, [this change enhance the throughput of `DictionaryBuilder` from 13.6% (Java 17 with Ubuntu 18.04)](https://github.com/KengoTODA/Sudachi/issues/1).
You may try to run the JMH microbenchmark to verify on your side:

```
$ cat <<EOF | git apply
diff --git a/pom.xml b/pom.xml
index e3f34d0..c73113a 100644
--- a/pom.xml
+++ b/pom.xml
@@ -230,6 +230,13 @@
             </manifest>
           </archive>
         </configuration>
+        <executions>
+          <execution>
+            <goals>
+              <goal>test-jar</goal>
+            </goals>
+          </execution>
+        </executions>
       </plugin>
       <plugin>
         <groupId>org.sonarsource.scanner.maven</groupId>
EOF

$ mvn clean package

$ java \
 -cp target/sudachi-0.5.4-SNAPSHOT.jar:target/test-classes/com/worksap/nlp/sudachi/dictionary/DictionaryBuilderPerformanceTest.class:~/.m2/repository/org/openjdk/jmh/jmh-core/1.33/jmh-core-1.33.jar:~/.m2/repository/net/sf/jopt-simple/jopt-simple/4.6/jopt-simple-4.6.jar:~/.m2/repository/org/apache/commons/commons-math3/3.2/commons-math3-3.2.jar:~/.m2/repository/com/worksap/nlp/jdartsclone/1.2.0/jdartsclone-1.2.0.jar:~/.m2/repository/org/glassfish/javax.json/1.1/javax.json-1.1.jar \
 com.worksap.nlp.sudachi.dictionary.DictionaryBuilderPerformanceTest
```

Thank you for checking my PR!
Hope that this change helps your work :)

### CODE REVIEW

**Comment by KengoTODA** [comment]
The build failed due to lack of GitHub Secrets:

> You're not authorized to run analysis. No sonar.login or SONAR_TOKEN env variable was set

Please rerun the GitHub Actions workflow run manually, then it can access GitHub Secrets and the build will succeed.

**Comment by eiennohito** [comment]
> The build failed due to lack of GitHub Secrets:

GitHub forbids using secrets in actions triggered by PRs from forks. Making a PR from a branch of this repo should work. We probably should do something with that, but I am not sure what.

**Comment by eiennohito** [comment]
I am not sure that placing JMH benchmarks as tests is the best course of action here.

**Comment by KengoTODA** [comment]
> I am not sure that placing JMH benchmarks as tests is the best course of action here.

It is possible to locate benchmarks into `src/jmh/java` or somewhere. I choose the current location just to minimize changes in `pom.xml`. 😊

**Comment by eiennohito** [comment]
I will probably add a lot more of them in the very near future (`jmh perfasm` is an extremely helpful tool for JVM performance work), so adding an infra with this PR is very appreciated.

**Comment by KengoTODA** [comment]
> Making a PR from a branch of this repo should work. We probably should do something with that, but I am not sure what.

I can propose two solutions:

1. Run the `sonar:sonar` goal only when the `SONAR_TOKEN` environment variable exists. Refer [the end of this blog post for detail](https://blog.kengo-toda.jp/entry/2020/06/21/175426). This is not so good if you want to use SonarQube analysis to evaluate potential problems in suggested changes.
2. Use `pull_request_target` event to trigger workflow runs. Refer [this blog post for detail](https://blog.kengo-toda.jp/entry/2021/08/30/092212), and refer [an official GitHub blog post](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/) to learn about security concerns around this usage.

Sorry but both blog posts are written in Japanese language. Please have a try with Google Translator or DeepL Translate if necessary :)

**Comment by KengoTODA** [comment]
> I will probably add a lot more of them in the very near future (jmh perfasm is an extremely helpful tool for JVM performance work), so adding an infra with this PR is very appreciated.

OK 👍 
Then I will put benchmarks into `src/jmh/java`, and apply the [maven-shade-plugin](https://maven.apache.org/plugins/maven-shade-plugin/) to generate a shaded jar file, then you can run any benchmark by `java -jar target/benchmarks.jar`. Is it acceptable for you?

**Comment by eiennohito** [comment]
Or because we (me and Takaoka-san) want to move to gradle anyways, maybe we should leave the things as they are and configure the gradle build as we want afterwards. Doing maven configuration now would be just a work that will be thrown away.

**Comment by eiennohito** [comment]
Using another code quality service which does not require to embed tokens in the builds is also an option.

**Comment by KengoTODA** [comment]
> Or because we (me and Takaoka-san) want to move to gradle anyways, 

Nice to hear this!

> maybe we should leave the things as they are and configure the gradle build as we want afterwards

OK, I'll wait your decision of course.

**Comment by eiennohito** [comment]
Ok, then please move benchmarks into `src/jmh/java`. Doing any maven configuration for making them actually runnable now is not needed.

**Comment by KengoTODA** [comment]
> Ok, then please move benchmarks into src/jmh/java. Doing any maven configuration for making them actually runnable now is not needed.

Finished. Thanks for your help!

**Review by eiennohito — APPROVED** [review]
Thank you for the fix!

**Pull request merged**
